### ISSUE TITLE
deadlocks on large stderr's

### ISSUE THREAD

**Issue by spiffomatic64** [licheng/gccfilter#4]
according to http://perldoc.perl.org/IPC/Open3.html this should be using select, and reading with sysread.

I was able to patch this in by building one large temporary buffer, splitting into new lines, and passing to gcc_stderr without too much change

**Comment by zed0** [comment]
This is apparently fixed in @dichlofos 's fork.  Might be nice to have that pulled in.

**Comment by dichlofos** [comment]
Wait a moment, I'll try to submit PR today :)

**Comment by dichlofos** [comment]
Here it is: https://github.com/licheng/gccfilter/pull/9
I've tested main functionality (coloring) and checked that coloring disable on redirection works, but as no unit tests supplied, I could suddenly broke smth else :)

**Comment by dichlofos** [comment]
Okay, this issue can be closed now?
